language: node_js
sudo: true
node_js:
  - 12
branchs:
  only:
    - master
addons:
  ssh_known_hosts:
    - 62.234.116.168:339
cache:
  directories:
    - node_modules
before_install:
  - chmod 600 ~/.ssh/id_rsa
  - openssl aes-256-cbc -K $encrypted_53dc3e94967b_key -iv $encrypted_53dc3e94967b_iv
    -in travis.enc -out ~/.ssh/id_rsa -d
  - echo -e "Host rmt\n\tHostname 62.234.116.168\n\tStrictHostKeyChecking no\n\tPort 339\n\tUser sorayama\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
install:
  - yarn
scripts:
  - yarn build
after_success:
  - scp -P 339 -r build rmt:myrepo/cqbot/views/
