language: node_js
sudo: true
node_js:
  - 12
branchs:
  only:
    - master
addons:
  ssh_known_hosts:
    - 62.234.116.168:339
cache:
  directories:
    - node_modules
install:
  - yarn
scripts:
  - yarn build
after_success:
  - chmod 600 ~/.ssh/id_rsa
before_install:
  - openssl aes-256-cbc -K $encrypted_53dc3e94967b_key -iv $encrypted_53dc3e94967b_iv
    -in travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - scp -P 339 -r build sorayama@62.234.116.168:myrepo/mini-kancolle-mis/build
